### ISSUE TITLE
update to line up with latest boostrap docs

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kss-bootstrap#17]
Some changes since 
http://getbootstrap.com/css/

**Comment by RobLoach** [comment]
Added more in https://github.com/kalamuna/kss-bootstrap/issues/28 .... We should put together a list of wanted styleguide sections to port over.

**Comment by RobLoach** [comment]
A lot more has been added. If we need more CSS/Javascript/component changes, feel free to create new issues with specific desired additions.
