### ISSUE TITLE
Revise presentation of Typography section

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kss-bootstrap#20]
at
http://test-kalastatic.at.kalamuna.com/styleguide/section-1.html
we say under the typography heading:

> "Use any of the available button classes to quickly create a styled button."

This doesn't line up with
http://getbootstrap.com/css/#type-headings

We're actually missing quite a bit here and are perhaps oversimplifying this section…

The visual hierarchy is also broken in absence of the panel/label around the example here and we may be introducing confusion in an effort to remove cruft.

![style_guide](https://cloud.githubusercontent.com/assets/249362/8792548/949237c8-2f1d-11e5-86ab-59c52021da86.png)

**Comment by RobLoach** [comment]
Three different things......

### 1. Breaks visual hirarcy

Remove Heading 1?

### 2. Typography Description
"The below provides typographical styles that are present across the entire site."?

### 3. This doesn't line up with http://getbootstrap.com/css/#type-headings

Think we should move the Typography section over to the CSS section?

**Comment by RobLoach** [comment]
1. Breaks visual hirarcy

This is desired, since we're showing how `h1` looks.

2. Typography Description

Fixed.

3. Doesn't line up with Bootstrap docs.

Fixed in https://github.com/kalamuna/kss-bootstrap/pull/28
