### ISSUE TITLE
When forking, error occurs

### ISSUE THREAD

**Issue by madeofpeople** [kalamuna/kss-bootstrap#24]
When forking this, before making any modifications, and running the script (in a kalastatic context).
[I was going to do some experiments in templating]

```
> kalastatic@ postbuild /****/sites/all/themes/eecs/kalastatic
> ./node_modules/kss-bootstrap/node_modules/kss/bin/kss-node --config='kss-node.json'
>> sh: ./node_modules/kss-bootstrap/node_modules/kss/bin/kss-node: No such file or directory
```
I fork, npm uninstall, npm install the fork....
Am i missing some step?

**Comment by RobLoach** [comment]
Fixed! :+1:
