### ISSUE TITLE
No "Bootstrappy" output ?

### ISSUE THREAD

**Issue by davekopecek** [kalamuna/kss-bootstrap#41]
After running:

```
kss-node node_modules/kss-bootstrap/styleguide out -t node_modules/kss-bootstrap/bootstrap
```

I get an out directory created, but hitting out/index.html or out/section-components.html does not give me any particularly `bootstrappy`  output. It looks like almost no CSS at all is being applied.  Zip of my /out directory is attached.

[out.zip](https://github.com/kalamuna/kss-bootstrap/files/366336/out.zip)

**Comment by RobLoach** [comment]
What version of KSS?
