### ISSUE TITLE
Upgrade to KSS 3

### ISSUE THREAD

**Issue by herrjosua** [kalamuna/kss-bootstrap#42]
I am getting the following error `unknown argument: t` when I try to run `npm-exec kss node_modules/kss-bootstrap/styleguide out -t node_modules/kss-bootstrap/bootstrap`. I have `kss` installed globally, `kss-bootstrap` repo checked out, and ran a `npm install` within the `kss-bootstrap` directory. I'm running node version `v4.2.3`, ,npm version `3.9.3` on OS X El Capitan version `10.11.6` .

**Comment by RobLoach** [comment]
Which version of kss are you using?

**Comment by herrjosua** [comment]
I am using KSS version `3.9.3`

**Comment by RobLoach** [comment]
Ah, it's targetting version 2 currently. Going to re-frame this issue to be Upgrade to 3 :+1: . Thanks a lot for the testing!

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kss-bootstrap/pull/43
